M48
; DRILL file {KiCad 9.0.3-9.0.3-0~ubuntu22.04.1} date 2025-10-17T13:31:58+0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-17T13:31:58+04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3-9.0.3-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X169.64Y-50.01
X186.34Y-50.01
M30
