M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu22.04.1} date 2026-03-18T15:25:32+0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-18T15:25:32+04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X169.64Y-50.01
X186.34Y-50.01
M30
